### ISSUE TITLE
Add Unifi server.log to logrotate config

### ISSUE THREAD

**Issue by JagerSprinkles** [linuxserver/docker-unifi-controller#144]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

I do not see logrotate being configured for '/usr/lib/unifi/logs/server.log' only for '/usr/lib/unifi/logs/mongod.log' I have checked all the files in /etc/logrotate.d/

Contents of /etc/logrotate.d/unifi
```
root@unifi-controller:/usr/lib/unifi# cat /etc/logrotate.d/unifi
/usr/lib/unifi/logs/mongod.log {
        rotate 5
        size 50M
        compress
        missingok
        sharedscripts
        su unifi unifi
        postrotate
                test ! -r /usr/lib/unifi/run/mongod.pid || kill -USR1 $(cat /usr/lib/unifi/run/mongod.pid)
        endscript
}
```

## Current Behavior

/usr/lib/unifi/logs/server.log is not rotated

## Alternatives Considered

I considered making my own container based off of this one but maintaining a container just to make sure the logs don't run away is a bit much.

I hope that maintaining the log size is in the scope for this container. (Also 50MB might be a little high for these logs)

**Comment by fermulator** [comment]
@github-actions bot go away (this is a value enhancement request)

**Comment by bmatheny** [comment]
@j0nnymoe is this something you are working on? I'd also like it. For whoever does work on it, the existing logrotate config doesn't come from docker-unifi-controller it comes from the mongo package. Since this image doesn't right now really do any configuration stuff besides system.properties, whoever puts together the PR for this would need to pull in the scaffolding to distribute configs. I think the linuxserver team has some of this already, but just a heads up.
