### ISSUE TITLE
Allow for Early Access builds to be used

### ISSUE THREAD

**Issue by bluenix** [linuxserver/docker-unifi-controller#148]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior
Use a tag to select the unifi Early Access release channel in order to use pre-release versions of the Unifi Network Application.

## Current Behavior
Only a tag to track stable releases is available.

## Alternatives Considered
Using other Docker containers, or using the apt repository.

**Comment by aptalca** [comment]
Even their stable releases are not very stable, can break installs, and often get pulled right after release. We have no interest in dabbling in their pre-release stuff. 

I personally wait at least a week or two before I update my production instance to a new stable and recommend everyone to do so.

**Comment by yllwfsh** [comment]
@aptalca Personally I don't have the same experience. Running their stable software without issues since about 2014. I think it would be interesting to be able to validate/test their pre-release software through this docker image. From time to time, Ubiquity releases extremely useful features.

It's of course up to the individual if they want to run the bleeding edge software or not. I don't think @bluenix was suggesting anyone run the pre-release in a production environment without proper validation.

**Comment by jasonafernandez** [comment]
I agree with @yllwfsh and @bluenix. I don't see how leaving a update option out is any different then other projects offered from linuxserver.io. For example, sonarr, radarr, plex, etc. all offer the ability to use beta or nightly update channels. Why should this be considered any different? Its the end users responsibility to have backups and understand the risks of running bleeding edge. A container is a container for a reason, if it blows up being unstable, so what.

**Comment by davlloyd** [comment]
+1 on this as would be good to get the RC releases available without having to "roll your own"

**Comment by j0nnymoe** [comment]
No plans to add this at this time as mentioned by @aptalca. 

While I agree with @jasonafernandez with saying it's the end users responsibility, for very 1 user than understands this could break their setup, there will be 10 that do it without thinking and will come to us complaining. Considering amount of support queries we get for Unifi normally, for now we aren't going to do this.

The reason this would be different to any other container is due to the fact that the unifi controller is a network applicance really and if it breaks, that's your network down where as if plex breaks, it's just media for a few hours.

Not saying never but for now, we don't plan to do this.
