### ISSUE TITLE
[BUG] /config/data/system.properties file is reset each deployment

### ISSUE THREAD

**Issue by PPCM** [linuxserver/docker-unifi-controller#202]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I need to modify the file /config/data/system.properties to add the property `smtp.checkserveridentity=false`
But when I do this modification, the system.properties file is reset to its original content after a redeploy

`/config` is a persistent volume

### Expected Behavior

When we modify the file system.properties, modification need to be persistant (this the easest way)
And other way, add an variable for custom properties

### Steps To Reproduce

1. Open the file `/config/data/system.properties`
2. Modify by adding the line `smtp.checkserveridentity=false` for example
3. Save the file
4. redploy the container
5. Open the file `/config/data/system.properties`
6. The added line doesn't exist

### Environment

```markdown
- OS:Debian 11
- How docker service was installed:Rancher 2.7.1
```

### CPU architecture

x86-64

### Docker creation

```bash
The creation was made with Rancher
All ports are exposed thru the load Balancer
Storage was added for /config
```

### Container logs

```bash
no log
```

**Comment by thespad** [comment]
We only copy the default file if there isn't one already present in /config (see https://github.com/linuxserver/docker-unifi-controller/blob/master/root/etc/s6-overlay/s6-rc.d/init-unifi-controller-config/run#L22-L24). If your file is being "reset" then either the controller software is doing it because you're editing the file while it's running, or your data is not being properly persisted, causing the default to be recopied on startup.

As you've provided no detail on how the container has been deployed, all I can do is speculate.
