### ISSUE TITLE
chown -R abc:abc /usr/lib/unifi is takeing > 60s

### ISSUE THREAD

**Issue by senax** [linuxserver/docker-unifi-controller#51]
Hi,

I run unify in kubernetes and had to increase the 'initialDelaySeconds' from 60 to 120 seconds because 'chown -R' is taking too long.

There are over 9000 root-owned files in /usr/lib/unifi which is causes significant delays each time unifi is started.

Would it be possible to chown in the Dockerfile perhaps?

I checked 'abc' on the base container where the uid is 911, on the unifi container it is 1000; not sure what is going on there.

Thanks

**Comment by j0nnymoe** [comment]
User's have experienced this on normal docker installed when the storage driver is overlay2. It's a bug that we can't do much about. But it also could be happening due to something with kubernetes, though we don't test/support this platform so we don't know for sure.

When the UID/GID 911, it means your values aren't being passed through properly.

**Comment by senax** [comment]
> When the UID/GID 911, it means your values aren't being passed through properly.
Ah, thanks. That was just from a simple manual 'docker run --rm -ti lsiobase/ubuntu:xenial sh' to see what's in the base container. In normal running is uses 1000.
