### ISSUE TITLE
EOL of Unifi Network Controller V5.8.30 and Below

### ISSUE THREAD

**Issue by backlands** [linuxserver/docker-unifi-controller#65]
The end of life for the Unifi Network Controller versions 5.8.30 and lower are approaching in January, emails are now going out and I just received one myself. The summary of the content of this email is quoted below:

> According to our records, you are using an out of date version of UniFi Network Controller. As of January 15, 2020, we will be shutting down certain legacy services which provide your network with remote management capabilities. These changes will affect all users with UniFi Network controllers version 5.8.30 or below. To avoid any disruption of service to your network, please log in to network.unifi.ui.com and update to the latest UniFi Network Controller by January 15th.

My controller is currently running the `LTS` 5.6.42 version of the docker and I have hesitated to move to `latest` simply because of some issues I have heard of for others moving to the new stable 6.x branch. It seems that with the end of life on January 15th the current `LTS` tag will no longer be accurate. Just wanted to bring this to the attention of the maintainers, feel free to close this issue if a plan is already in place.

**Comment by aptalca** [comment]
Thanks for the heads up. It's entirely an upstream change. They used to have a long-term-stable track, which was somewhat closely following the latest release. But they must have changed that strategy because the long-term-stable hasn't moved from 5.6 in a long time while the latest has been 6.X for a while.

With that said, our `latest` tag uses their apt repo packages, which are slightly delayed compared to the web releases. There have been some releases that were pulled after the web release. Unifi seems to be using the web releases as a test to see if it breaks users' stuff and if so, they pull it before it hits the apt repo. Our users were protected in those cases.

We'll likely go ahead and deprecate the `LTS` tag by the end of the year.

**Comment by backlands** [comment]
Great, thanks for the additional info on this @aptalca and good to hear that users of this image were protected from the issues that were hitting other users on the 6.x releases. The info you provided gives me confidence in updating during my upcoming holidays to the `latest` tag. Thanks again!

**Comment by backlands** [comment]
Just providing a follow up that I upgraded from the `LTS` tag to the `latest` tag on the 20th of December and the upgrade went smoothly overall with only a couple minutes of downtime. Network has been stable since the migration as well. Looks like the migrations between those branches from Unifi are solid at the moment.

I know this comment doesn't relate directly to the docker provided here and is more general, but I wanted to note that it was a fairly quick process for any other users that might find this thread.

**Comment by aptalca** [comment]
@backlands thanks for the info. Out of curiosity, did you go straight from lts to latest? A little while ago, some people reported getting errors in unifi when trying to go direct where unifi said it couldn't update due to version being too old? They had to first update to an older tag, and then to latest. I haven't had a chance to test myself.

Thanks

**Comment by backlands** [comment]
@aptalca that is correct, I did a direct upgrade from `5.6.42` to the newest version on `latest` at the time, which looks to have been `6.0.41`. The newer `6.0.43` was released after I upgraded and I am not seeing a `6.0.42` on their download portal for the controller software. I did not have to upgrade to another tag before going into `latest`.

**Comment by aptalca** [comment]
Excellent. Thanks for the confirmation. We'll go ahead and deprecate the LTS tag and put a note in the readme and container log

**Comment by backlands** [comment]
Glad I could be of help, hopefully the transition is as smooth for everyone else as it was for me!
