### ISSUE TITLE
Use https downloads from Ubiquiti and MonogoDB

### ISSUE THREAD

**Issue by countableSet** [linuxserver/docker-unifi-controller#9]
I'm not sure what the history is behind using http endpoints for downloads, but it would be nice if you guys switched over to https.

Unifi deb package download can be moved to it, e.g.
```
https://dl.ubnt.com/unifi/5.10.20/unifi_sysvinit_all.deb
```
here:
https://github.com/linuxserver/docker-unifi-controller/blob/126b7e8adea4f370bf9b23a832a1e5b8558784f7/Dockerfile#L35

Unif package version lookup doesn't appear to have an https version :disappointed: 
https://github.com/linuxserver/docker-unifi-controller/blob/126b7e8adea4f370bf9b23a832a1e5b8558784f7/Dockerfile#L28

MongoDB docs also has an https repo, e.g.
https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/
```
echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.0.list
```
here https://github.com/linuxserver/docker-unifi-controller/blob/126b7e8adea4f370bf9b23a832a1e5b8558784f7/Dockerfile#L17

**Comment by aptalca** [comment]
Can you make a strong case for using https endpoints for repos? I'm not convinced there is any benefit

**Comment by loganmarchione** [comment]
@aptalca  - Is there any drawback to using HTTPS? The overhead of using HTTPS should be near zero. Your image is built on Ubuntu, so it should have all the necessary packages for checking HTTPS URLs (as opposed to a super-minimal base like Alpine).

As far as @countableSet's points:
1) You're downloading `unifi_sysvinit_all.deb` with curl straight from Ubiquiti over HTTP. Why is this not HTTPS? At least if you used APT, it would check GPG keys (as with Mongo, below).

2) If there isn't an HTTPS URL for `http://dl-origin.ubnt.com/unifi/debian/dists/${UNIFI_BRANCH}/ubiquiti/binary-amd64/Packages`, that's out of our control. Nothing we can do.

3) Unlike above, Mongo [does not need to use HTTPS](https://whydoesaptnotusehttps.com/), because APT is checking if the package is signed with Mongo's GPG key. However, there was a [recent vulnerability in apt](https://justi.cz/security/2019/01/22/apt-rce.html), where the finder stated:

> I wouldn’t have been able to exploit the Dockerfile at the top of this post if the default package servers had been using https.


In my opinion, you should either:
1) Use HTTPS for downloading the `unifi_sysvinit_all.deb` file via curl
2) Switch to adding the Ubiquiti repo and installing unifi via that repo (which will allow APT to check GPG keys), instead of using curl

**Comment by aptalca** [comment]
The article you linked also mentions that there was a vulnerability in apt and it was fixed, so that is no longer an issue. There could very well be a different vulnerability that affects https, no guarantees.

I'll ask again, what strong benefit does https provide? If the upstream server is compromised, it doesn't matter whether we use http or https. If the dns servers are compromised, they can easily generate valid certs for a hijacking server. If our jenkins is compromised, well, then there are larger issues.

In our case where the Dockerfiles are used by our jenkins to build the images, the only difference really is https communication is encrypted whereas http is not. That doesn't serve us any benefit at all as we don't transfer any sensitive info, merely downloading packages.

Using https on the other hand has occasionally caused issues that led to build failures due to invalid certs and other various server misconfiguration issues.

https://whydoesaptnotusehttps.com/

**Comment by thelamer** [comment]
I agree with @aptalca here, if this was in a different location and not inside of our own self hosted build environment I think we should consider it (IE a user consumable script).
